name 'chef-tomcat-appli'
maintainer 'PE, pf.'
maintainer_email 'peychart@mail.pf'
license 'GNU Public License 3.0'
description 'Installs/Configures chef-tomcat-appli'
long_description 'Installs/Configures chef-tomcat-appli'
version '0.1.0'

depends 'apt'
depends 'java'
depends 'tomcat'
